# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#' 
#' @param x A single integer.
#' @export
myfunc_wrapper <- function(M, multiplier) {
    invisible(.Call(`_gconcord_myfunc_wrapper`, M, multiplier))
}

#' Multiply a number by two
#' 
#' @param x A single integer.
#' @param y *A* *single* integer.
#' @export
qwer <- function(x, y) {
    .Call(`_gconcord_qwer`, x, y)
}

